apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        name: db
    name: db
spec:
    replicas: 1
    selector:
        matchLabels:
            app: db
            service: db
    template:
        metadata:
            labels:
                app: db
                service: db
        spec:
            containers:
                -
                    name: db
                    image: docker.io/mithunhr/dbmongo:latest
                    imagePullPolicy: IfNotPresent
                    ports:
                    - containerPort: 27017
