apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        name: mong
    name: mong
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mong
            service: mong
    template:
        metadata:
            labels:
                app: mong
                service: mong
        spec:
            containers:
                -
                    name: mong
                    image: docker.io/mithunhr/dbmongo:latest
                    imagePullPolicy: IfNotPresent
                    ports:
                    - containerPort: 27017
