apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    service: mong
  name: mong
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    service: mong
status:
  loadBalancer: {}
