apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    service: db
  name: db
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    service: db
status:
  loadBalancer: {}
