apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        name: node
    name: node
    namespace: harsha
spec:
    replicas: 1
    selector:
        matchLabels:
            app: node
    template:
        metadata:
            labels:
                app: node
        spec:
            containers:
                -
                    name: node
                    image: docker.io/mithunhr/appnode:latest
                    imagePullPolicy: IfNotPresent
                    ports:
                    - containerPort: 3000
                    restartPolicy: Always
