apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        name: api
    name: api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: api
            service: api
    template:
        metadata:
            labels:
                app: api
                service: api
        spec:
            containers:
                -
                    name: api
                    image: docker.io/mithunhr/appnode:latest
                    imagePullPolicy: IfNotPresent
                    ports:
                    - containerPort: 8080
