apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    service: api
  name: api
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: api
status:
  loadBalancer: {}
